### ISSUE TITLE
Correct folder structure

### ISSUE THREAD

**Issue by DorinaSobiecki** [schule4-0/planets#18]
Correct folder structure so that we do not have unnecessary empty folders at the beginning.

**Comment by lgastler** [comment]
@mastoeppler @DorinaSobiecki This change will make the deployments fail, since it is looking for the app inside "Frontend/planets" please ping me when this gets merged, so I can adjust the deployment.

**Comment by SebastianMaier03** [comment]
@lgastler Changes merged to Main. Please adapt Deploy
